Users manage page
aleksaalfir/nqode-intentship pull request #10
Opened 2022-11-16 17:11 UTC by aleksaalfir

A page where the administrator can see all users and where he can manage them...

2022-11-17 07:59 UTC, petarnqode requested changes

2022-11-17 07:59 UTC, petarnqode commented on src/components/Users/User/User.tsx
> +const User: React.FC<UserProps> = ({user, editUser, deleteUser}) => {
Can we dest object agin, exp. { user :{ title, startRentDate, endRentDate }, editUser, deleteUser }

2022-11-18 11:10 UTC, vkotarlic requested changes

2022-11-18 11:10 UTC, vkotarlic commented on src/components/Users/User/User.module.scss
> +    color: $color-white;
`text-align` and `color` should be grouped together

2022-11-18 11:10 UTC, vkotarlic commented on src/components/Users/User/User.tsx
> +  const changeUserValueHandler = (value : string,  prop?: string) =>{
Please add space after `=>`

2022-11-18 11:10 UTC, vkotarlic commented on src/components/Users/User/User.tsx
> +                placeholder={'first name'}
Could you please format this placeholder to be `First name` or `Please enter first name`

2022-11-18 11:10 UTC, vkotarlic commented on src/components/Users/User/User.tsx
> +                placeholder={'last name'}
Could you adjust this placeholder as it is suggested in comment above

2022-11-18 11:10 UTC, vkotarlic commented on src/components/Users/User/User.tsx
> +                placeholder={'phone number'}
Could you adjust this placeholder as it is suggested in comment above

2022-11-18 11:10 UTC, vkotarlic commented on src/components/Users/User/User.tsx
> +                  placeholder={'address'}
Could you adjust this placeholder as it is suggested in comment above

2022-11-18 11:10 UTC, vkotarlic commented on src/components/Users/User/User.module.scss
> +  &__last {
What is `__last` i think this class should be named something more meaningful

2022-11-18 11:10 UTC, vkotarlic commented on src/components/Users/User/User.tsx
> +              <div className={classes['c-user__last']}>
Please check comment in scss about `__last`

2022-11-18 11:10 UTC, vkotarlic commented on src/components/Users/Users.tsx
> +        toastService.toastError(`${err.response.data.message}`);
Please add some error message for this don't use backend one

2022-11-18 11:10 UTC, vkotarlic commented on src/components/Users/Users.tsx
> +        toastService.toastError(`${err.response.data.message}`);
Please add some error message for this don't use backend one

2022-11-18 11:10 UTC, vkotarlic commented on src/pages/Login/Login.tsx
> +        console.log("aaaa");
Please remove this console.log 😆

2022-11-18 11:10 UTC, vkotarlic commented on src/services/toastService.tsx
> +// IMPORT <ToastContainer/> in component where you want to use toastService
Please remove this comment it doesn't have any purpose

2022-11-18 11:10 UTC, vkotarlic commented on src/services/toastService.tsx
> +}
Please format this code with prettier

2022-11-18 13:20 UTC, merged