NavBar links and routes implemented
aleksaalfir/nqode-intentship pull request #14
Opened 2022-11-21 11:05 UTC by aleksaalfir

Nav bar links are now displaying based on user role. User now gets redirected if he tries to visit unauthorised route.

2022-11-21 12:18 UTC, milos-majkic approved these changes

2022-11-21 15:07 UTC, petarnqode requested changes

2022-11-21 15:07 UTC, petarnqode commented on src/pages/BooksPage/BooksPage.tsx
> +      const dataBooks: Book[] = data.content;
Can we do this in other way, const { content : dataBooks } = data; ?

2022-11-21 15:07 UTC, petarnqode commented on src/pages/BooksPage/BooksPage.tsx
> +              numOfCopies={book.numOfCopies}
This can get messy, can we send book obj and destruct in component or {...book} ?

2022-11-22 10:37 UTC, vkotarlic requested changes

2022-11-22 10:37 UTC, vkotarlic commented on src/App.tsx
> +            />
I would like to handle this in different way

2022-11-22 10:37 UTC, vkotarlic commented on src/components/Layout/Header/Header.tsx
> +          })}
It is same for this part, you are mapping list of links but i don't think it is good idea

2022-11-22 10:37 UTC, vkotarlic commented on src/pages/BooksPage/BooksPage.tsx
> +        )
I would like to filter books outside of setState and then just set them

2022-11-22 10:52 UTC, aleksaalfir commented on src/App.tsx
> +            />
Can i have an additional explanation?

2022-11-23 08:13 UTC, merged