Admin now have a dashboard view
aleksaalfir/nqode-intentship pull request #15
Opened 2022-11-23 10:32 UTC by aleksaalfir

Admin now have a dashboard view where he can see books, users and rents section. Books section is default.

2022-11-23 12:17 UTC, milos-majkic requested changes

2022-11-23 12:17 UTC, milos-majkic commented on src/components/Layout/Dashboard/Dashboard.tsx
> +    if (pathname === '/dashboard' || pathname === '/dashboard/') {
I'm not sure why you have '/dashboard' and '/dashboard/'

2022-11-23 15:05 UTC, aleksaalfir commented on src/components/Layout/Dashboard/Dashboard.tsx
> +    if (pathname === '/dashboard' || pathname === '/dashboard/') {
I need to redirect user from /dashboard and /dashboard/ because i dont have any welcoming page on that route. It is showing only side bar.

2022-11-25 12:41 UTC, vkotarlic requested changes

2022-11-25 12:41 UTC, vkotarlic commented on public/index.html
> +    />
Fonts should be imported in scss with `@import` or downloaded and imported by hand in `_fonts.scss` file

2022-11-25 12:41 UTC, vkotarlic commented on public/index.html
>      <title>React App</title>
Maybe it is good idea to change title of the app :)

2022-11-25 12:41 UTC, vkotarlic commented on src/components/Layout/Dashboard/Dashboard.module.scss
> +    width: 3%;
Why width is 3%? I think it is better to set it to something with `vw`

2022-11-25 12:41 UTC, vkotarlic commented on src/components/Layout/Dashboard/Dashboard.module.scss
> +  }
This is not good because you are repeating styles and going against BEM rules

2022-11-25 12:41 UTC, vkotarlic commented on src/components/Layout/Dashboard/Dashboard.module.scss
> +    text-decoration: none;
I would like to move this to index.scss or any kind of global style and remove it on all places

2022-11-25 12:41 UTC, vkotarlic commented on src/components/core/Button/Button.module.scss
> +  // margin-right: $space-s;
Please remove this comment

2022-11-25 12:41 UTC, vkotarlic commented on src/pages/Admin/CreateBookPage/CreateBookPage.tsx
> +      .then(() => {})
Why we have empty `then` block

2022-11-25 12:41 UTC, vkotarlic commented on src/pages/Admin/CreateBookPage/CreateBookPage.tsx
> +  document.title = 'Add book';
Please don't set document tile like this, set one title in index.html

2022-11-25 13:23 UTC, merged