Created Login page and added React Router to the project
aleksaalfir/nqode-intentship pull request #2
Opened 2022-11-08 13:34 UTC by aleksaalfir

Login page is not communicating with any API-s. Its just a simulation action for submit button. Small changes done on non-related files.

2022-11-08 14:26 UTC, milos-majkic requested changes

2022-11-08 14:26 UTC, milos-majkic commented on src/components/Login/Login.module.scss
> +        font-size: 6rem;
Use variables instead of fixed values

2022-11-08 14:26 UTC, milos-majkic commented on src/components/Login/Login.module.scss
> +        margin-top: 15px;
Also, remove fixed values

2022-11-08 14:26 UTC, milos-majkic commented on src/components/Login/Login.module.scss
> +}
Configure .prettier to add a new line at the end of the file

2022-11-08 14:26 UTC, milos-majkic commented on src/components/core/Button/Button.module.scss
> +    border-radius: 6px;
Remove fixed values

2022-11-08 14:26 UTC, milos-majkic commented on src/components/core/Button/Button.module.scss
> +}
New line at the end of the file

2022-11-08 14:26 UTC, milos-majkic commented on src/components/core/Input/Input.module.scss
> +        margin-bottom: 5px;
Fixed value

2022-11-08 14:26 UTC, milos-majkic commented on src/components/core/Input/Input.module.scss
> +        border-radius: 5px;
Fixed values

2022-11-08 14:26 UTC, milos-majkic commented on src/components/core/Input/Input.module.scss
> +}
Add new line

2022-11-08 15:58 UTC, vkotarlic approved these changes
Good job!

2022-11-08 15:58 UTC, vkotarlic commented on src/components/core/Input/Input.tsx
> +  label: string;
Here I would suggest setting label to be optional param, because sometimes we want only input field without it

2022-11-08 15:58 UTC, vkotarlic commented on src/components/core/Input/Input.tsx
> +      </label>
Since I suggested changing label to be optional, conditional rendering should be used on line 16.

2022-11-09 08:16 UTC, milos-majkic approved these changes

2022-11-09 08:17 UTC, merged