Login is now communicating with backed app
aleksaalfir/nqode-intentship pull request #3
Opened 2022-11-09 14:18 UTC by aleksaalfir

Created login function that saves token to local storage. Created functions for decoding jwt, getting role from jwt and checking if role is administrator

2022-11-09 14:31 UTC, milos-majkic requested changes

2022-11-09 14:31 UTC, milos-majkic commented on .env
> +REACT_APP_BACKEND_URL=http://localhost:8080
Could you please add a new line at the end of the file

2022-11-09 14:31 UTC, milos-majkic commented on src/pages/Login/Login.tsx
> +import authService from 'services/auth-service';
This isn't a proper name for the service, you need to change it to AuthService.ts

2022-11-09 14:31 UTC, milos-majkic commented on src/services/auth-service.tsx
> +export default AuthService;
Please, change auth-service.tsx to AuthService.ts name

2022-11-09 15:01 UTC, vkotarlic requested changes

2022-11-09 15:01 UTC, vkotarlic commented on src/pages/Login/Login.tsx
>  import React from 'react';
Can you please move React import to top of this file

2022-11-09 15:01 UTC, vkotarlic commented on src/pages/Login/Login.tsx
> +    axios.post(backend_url + '/authenticate', loginData).then((response) => {
Please use template literals for all string concatenations

2022-11-09 15:01 UTC, vkotarlic commented on src/pages/Login/Login.tsx
> +        return alert('Welcome.');
It is not good idea to use `alert()` function, because it throws alert to user and can look sketchy. Better thing here would be to use some kind of toast message. Also user should be redirected to next page after login

2022-11-09 15:01 UTC, vkotarlic commented on src/pages/Login/Login.tsx
> +      setInputError(true);
It is good idea to use `.catch()` part of promise to handle all errors

2022-11-09 15:01 UTC, vkotarlic commented on src/services/AuthService.tsx
> +
I would like to discuss this whole file with you

2022-11-10 11:57 UTC, vkotarlic approved these changes

2022-11-10 11:57 UTC, merged