Admin CRUD for book
aleksaalfir/nqode-intentship pull request #5
Opened 2022-11-10 16:11 UTC by aleksaalfir

Crud page for single book that admin can see.

2022-11-14 09:09 UTC, milos-majkic requested changes

2022-11-14 09:09 UTC, milos-majkic commented on src/components/BookDetails/BookDetails.tsx
> +        console.log(res);
Please, remove this console.log

2022-11-14 09:09 UTC, milos-majkic commented on src/components/BookDetails/BookDetails.tsx
> +      .catch((err) => console.log(err));
Also, remove this log

2022-11-14 09:09 UTC, milos-majkic commented on src/index.tsx
> +  console.error(`[response error] [${JSON.stringify(error)}]`);
When you finished testing some functionality, need to remove all logs.

2022-11-14 09:09 UTC, milos-majkic commented on src/pages/Login/Login.tsx
> +        console.log(err.status);
Remove this

2022-11-18 08:35 UTC, vkotarlic requested changes

2022-11-18 08:35 UTC, vkotarlic commented on src/components/BookDetails/BookDetails.tsx
> +          placeholder={'Title...'}
I would suggest to say something like 'Please enter title' or just 'Title' here and not 'Title...'

2022-11-18 08:35 UTC, vkotarlic commented on src/components/BookDetails/BookDetails.tsx
> +            placeholder={'Author...'}
I would suggest to say something like 'Please enter author name' or just 'Author' here and not 'Author...'

2022-11-18 08:35 UTC, vkotarlic commented on src/components/BookDetails/BookDetails.tsx
> +            placeholder={'Description...'}
I would suggest to say something like 'Please enter book description' or just 'Description' here and not 'Description...'

2022-11-18 08:35 UTC, vkotarlic commented on src/components/BookDetails/BookDetails.tsx
> +          <Button name="Delete" type="danger" clickHandler={deleteBookHandler}></Button>
Here close button with `/>` because it doesn't have children

2022-11-18 08:35 UTC, vkotarlic commented on src/components/core/Button/Button.tsx
> +      }
I would like for you to refactor this no need to check for type as it is string and it is mandatory so you can just use it

2022-11-18 08:52 UTC, aleksaalfir commented on src/components/core/Button/Button.tsx
> +      }
I've changed the code, but i'm not sure if you wanted it like that. Can you check it please?

2022-11-18 08:55 UTC, merged